### ISSUE TITLE
Custom ASCII per terminal

### ISSUE THREAD

**Issue by IkeoMajesty** [CodaBool/terminal#1]
Great idea for a module but making the logo a global setting makes it unusable for me (logo feature, not the module itself) I can't think of one setting (except single starship exploration or haist on a specific place so single scenario usage) where there are not multiple organizations.

One solution would be to make it a per-terminal setting. 

Also, it would be nice to be able to pull the text from a pre-generated file.

**Comment by CodaBool** [comment]
Definitely see the value in a per terminal ASCII. 

My next set of features was going to be around style and audio. 

So this actually gives me a great path to head down. 

The vision for it is you have maybe 3 starter styles and you can create (as many as you want) new custom ones.

A style would initially be composed of two things but will be expanded on with more updates. To include things like optional audio to play on boot.

- 3 colors (shadow, base, highlight)
- ASCII art

Then when creating a terminal tile you select the style in a drop-down.

To your other point. I'm not totally sure what you mean with a pre-generated file. Can you explain that more?

**Comment by IkeoMajesty** [comment]
Great news!
That will indeed be great. 

I give you a user story:

Adam wants to use a few different logos in a few of his games. He plays Fallout 2d20.
He knows that in the Fallout setting there are few organizations but he will be using only three: Enclave, BoS, and Vault Tech.
He wanted to prepare ahead of time so he made three files with logos: enclave.txt, bos.txt, vt.txt.
He has to copy this logo and paste it into the editor in each of the terminal instances. 

If there was a file picker that allows you to choose a text file with precomposed ASCII code for a logo it would greatly improve the UX.

**Comment by CodaBool** [comment]
Ok gotcha. Yeah a drop-down where you can pick your custom style should solve that UX issue.

I'm speaking to a UX that I haven't made yet. So bear with me but it'd be something like this: Adam would create 3 custom styles. In some new form I'd make. Each time entering a new ASCII. Setting color and audio to match the styles for the 3 factions. Finishing each one with a label for the faction name.

Then whenever a new terminal gets created there would be a drop down in the tile settings where you pick the style. So if you labeled a style Enclave you'd select that for an Enclave styled terminal.

**Comment by IkeoMajesty** [comment]
After you wrote that I realized styles will work just as well if not better. Thank you!

**Comment by CodaBool** [comment]
code has been written for non-global styling, and has no obvious bugs :smile: 

Not that I think this issue will have a ton of views so I'll keep the poll requirement low.
I'm going to shoot for including the audio in this same version, which will delay its release. 
If this gets, let's say 3 :rocket: reactions, I can save the audio update for another release and just put out what I have now.

But if not I'll see about getting a v1.2.0 out in the next few weeks with a major styling overhaul.

**Comment by CodaBool** [comment]
https://youtu.be/8W2ehPG8YTc

going to give it some polish but all the features are there for v1.2

**Comment by CodaBool** [comment]
# v1.2.0 Released :tada: 

[changelog](https://codabool.itch.io/terminal/devlog/655582/version-120-release)
