### ISSUE TITLE
[REQUEST] - Secure Shell button renaming

### ISSUE THREAD

**Issue by Flatline42** [CodaBool/terminal#10]
I'm running Cyberpunk and I love the idea of the secure shell not just for accessing another terminal but for data shards and all kinds of fun inventory based stuff. 

Towards that end, I'd love the ability to rename the secure shell button. Maybe have that as an option to store as a variable when setting up the terminal style? The tile properties for the terminal works too depending on the use scenario. Off/blank would default to Secure Shell, on and with a value would be the new name.  You're already pulling button names in the terminal from the journal titles so I'm guessing this is doable within the framework of the module. 

Might be more coding than it's worth. It's a small QOL request.

**Comment by CodaBool** [comment]
totally doable and actually not much code at all. At one point I was worried about stuffing too many fields into the tile config. But I now have some fields only show if the parent config is in use. Which keeps the config appearing slim while still having lots of customization.

In this case a new button name field can pop if the Secure Shell is checked. I can see about adding this sometime this month.

**Comment by CodaBool** [comment]
Should be all done. Just 15 lines of code. Pushing out version 2.6.3 now

**Comment by Flatline42** [comment]
Awesome thank you for the great module! I appreciate it!
