### ISSUE TITLE
[REQUEST] - Renaming Door and Macro buttons

### ISSUE THREAD

**Issue by Vespilo** [CodaBool/terminal#11]
**Is your feature request related to a problem? Please describe.**
When having a console controlling multiple things at once in a large map, macros and door controls can be very confusing, leading to two feature requests. While The macro buttons have different names set by the associated macro, it'd be easier to rename them if using the same macro with different arguments.

1. The ability to rename buttons and macros
2. Hiding macro buttons that are set to be only executed once

**Describe the solution you'd like**
1. A way to rename the buttons, e.g. in the field itself by parsing it with a descriptor `UUID | Toggle Armory Locks`

**Describe alternatives you've considered**
Providing a list with door names in the terminal itself as a workaround is possible, but cumbersome

**Comment by CodaBool** [comment]
These are solid improvements. I'll look into these.

**Comment by CodaBool** [comment]
### Small Update

I've gotten a prototype of this done. Currently supports renaming these buttons:

- run macro button
- Observe Actor button
- Secure Shell button
- Monk's Run Triggers button
- any number of door buttons

> This will be easily expandable going forward. So, if anyone requests another button to be supported for renaming it should be simple.

### Delay
I'm going to bundle it with a new rework I have coming up (fully rewrite the Terminal window into AppV2). Which will delay this feature.

**Comment by CodaBool** [comment]
version 3 has been released. Which has this rename feature included in it.

> unfortunately this is V12+ ONLY. Since I'm no longer supporting new features for V10-11.

A detailed post about it is [here](https://codabool.itch.io/terminal/devlog/786464/terminal-v30)
