### ISSUE TITLE
[REQUEST] - Scripts instead of macros

### ISSUE THREAD

**Issue by Vespilo** [CodaBool/terminal#12]
**Is your feature request related to a problem? Please describe.**
With the introduction of Foundry V12's region we got new ways to execute scripts without having to amass macros. I'm not sure if it is possible for a module to use it the same way, but it would clean up the macro collection if scripts could directly be put into the terminal's button functionality

**Describe the solution you'd like**
A field or dialog for adding buttons to the console that can execute scripts rather than macros, similar to the region behavior options

**Describe alternatives you've considered**
Macros as usual are viable, it's merely a QOL feature that I'm not sure can be implemented or not

**Additional context**
![image](https://github.com/user-attachments/assets/f6d76920-e1d0-4984-87ec-5ff144df7ab5)

**Comment by CodaBool** [comment]
The Foundry source code isn't difficult to look into. I'll take some time to see how they do it.

It is definitely possible for a module to do this. I have seen a theripper93 module do this. Might have been the puzzle one, not sure.

**Comment by CodaBool** [comment]
Started a prototype but having second thoughts on how useful this will be. It is easier for me to just support Macros and not have the overhead of another way of running code.

> prototype, (it's just UI, didn't code out running a script)

![image](https://github.com/user-attachments/assets/88dd62bb-4f54-493f-b057-e0bd7213e550)


There currently is two ways of running code. There is the current macro method but there is also integration with Monk's Active Tile Triggers. I checked and they actually have a way to run inline code like you are wanting. I think that would be my recommendation for you to help clean up your macros (assuming you have already looked into the obvious solution of folders). 


> all that is needed is an active Monk's Active Tile Triggers module and you'll see the new checkbox

![image](https://github.com/user-attachments/assets/f44fbca0-c775-4f70-a8a7-6eda7a8003f9)





> Follow the hover tooltip instructions to remove the default "When: Enter". Then write a trigger for "run code" like this

![image](https://github.com/user-attachments/assets/7698b4cf-46a4-442e-b60a-11b7836a5d1d)

**Comment by CodaBool** [comment]
I will add support for executing region behaviors in a future update. That should be a good way to allow for inline scripts without any additional modules.
