### ISSUE TITLE
[BUG] - Some bugs with terminal closing and extra.

### ISSUE THREAD

**Issue by Furukia** [CodaBool/terminal#13]
Hi. Bought you module not so long ago. Love it. But it has some bugs i unfortunately found which i'll describe below. Also i got some suggestions to improve it, but i'll post them in a different issue.

## Bugs
- On terminal window close, reveal dialog sometimes occures more than one time and doesn't close the window. Doesn't matter which button on it you click. Also dublicates the red text("This is a copy of what players would see e.t.c.") when it happens on gm side. 

> Here's a screenshot of a second "reveal" window. That has been opened after i closed the first and tried again to close the main terminal window.
![image](https://github.com/user-attachments/assets/80307177-0b1b-4c5b-9bc2-c3f464b72b26)

- When player gets a "skill check" terminal unlocked, a window with "You've found this computer terminal, but getting access will not be easy..." text doesn't close. Weirdly enough it gets marked as pinned by module "window controls" my guess is there's some sort of conflict there... Probably because of this module header modifications?
- Decode header animation doesn't work if the header is in other language than English. At least it doesn't work with Russian. *shrug*

## Minor flaws
- I don't get the point of "Replace Tile Image" button. Is it really necessary? 
	- Maybe it can be made more useful by creating a setting to store a default image. 
	- Or even images. And if there are multiple images you can make a simple selector grid with all setup images, which will speed up the process of tile creation. Example: Foundry filepicker's files grid.

## Spelling
- Observe Token(s) hint: owernship -> ownership
> Screenshot
![image](https://github.com/user-attachments/assets/0481d0b0-7708-4cd7-8649-301c6e611b2f)

I believe a saw some extra spelling mistakes, but i can't find them now)

## Setup:
 - Foundry Version: 12.330
 - Game System Version: yzecoriolis v3.9.1
 - Terminal Module Version: 2.6.3 
 - Browser & version: Most of the bugs occured inside Foundry window. Bugs found from player view were on Vivaldi 6.8.3381.48

## Active modules:
Honestly i have exactly 154 active modules XD 
But i think the only relevant one that i presume has some conflicts was already mentioned here:
- Window controls

Other modules i think don't modify any functionality that can conflict with your module. But if you need i can later check on a fresh world without any modules.

**Comment by CodaBool** [comment]
> reveal dialog sometimes occures more than one time

Are you on The Forge? 




> Decode header animation doesn't work

So, I can totally get why this would be partially broken for Russian. It works by first scrambling the text into random English letters. Then corrects them character by character. 

When you are saying it's broken, what is it's behavior? 

One thing to check for it is it's very picky on the header tag not having any children. Check in the source view and review any children. (Another requirement is that it must be header 1-3)

> Replace Tile Image

It's supposed to replace the tile texture image. Is it not doing that?



I have time to get these fixed this weekend. Ill get a patch out soon. Thanks for bringing them to my attention

**Comment by Furukia** [comment]
> Are you on The Forge?

Nope, i am not on the forge. Local installation

> One thing to check for it is it's very picky on the header tag not having any children. Check in the source view and review any children.

Yea, sorry. It actually works if the header doesn't contain any childrens. 

> It's supposed to replace the tile texture image. Is it not doing that?

It's doing it, i just don't understand the idea behing replacing it as a single preditermined image. This can basicly be done by a standart foundry interface... so it looks kinda unnecessary?

Also i found one thing in your css that i think you should fix
this rule:
`.terminal-textbox h1, h2, h3`
changes all h2 and h3 headers. it should probably look like this:
`.terminal-textbox h1, .terminal-textbox h2, .terminal-textbox h3` 
so it will only change headers in terminal

**Comment by CodaBool** [comment]
>  This can basically be done by a standard foundry interface

right, it's supposed to be quick QoL thing. I use it all the time. I especially find it useful in V12 because now tiles without a texture do not even show when in Token Controls view. So, getting a tile setup as quick as possible is useful. 

I do think it could be improved by making it a selection of a couple designs. Instead of just the one.

### CSS header
oh nice, I should do that.

**Comment by CodaBool** [comment]
>  reveal dialog sometimes occurs more than one time

could you provide steps for how to reproduce this? I'm having trouble recreating this. 

I've "fixed" this issue once by making the audio load async. Not sure why it would be happening now.

**Comment by Furukia** [comment]
> could you provide steps for how to reproduce this? I'm having trouble recreating this.

Here's an example gif a quickly made (it's sped up to preserve space so i can post it here). It shows how the problem looks. It basicly happens when you try to close the terminal, almost 90% of the times for me. Console is silent, so no warning's or errors to provide, sadly. 
![example](https://github.com/user-attachments/assets/048b69d7-4f90-48cb-ab83-83ba331fdd0b)

**Comment by CodaBool** [comment]
Does this happen with the `window-controls` module disabled?

**Comment by Furukia** [comment]
> Does this happen with the `window-controls` module disabled?

Just tested out. It doesn't. There's definetely a conflict there. 
Which is honestly kinda sad. Window control is a preaty neat module.

**Comment by CodaBool** [comment]
No, that's actually good. I already have a fix locally that supports `window-controls`. Which I'm guessing will solve this issue as well. I'll push this out. It should be downloadable in an hour.

**Comment by Furukia** [comment]
Thanks!
