### ISSUE TITLE
[BUG] - Terminal does not update journal page position

### ISSUE THREAD

**Issue by Upgradecap** [CodaBool/terminal#15]
Hi! I discovered a bug regarding page position in a journal linked to the terminal. It seems that the terminal does not automatically update what position/number a page has in the journal if you update the page position after creating it.

For example: I create three pages called page 1, page 2 and page 3. Then i want to re-arrange the order of the pages in the journal after i've created them, eg i move page 3 to page 2's position so that page 3 is now page 2 in the journal order. In the terminal it will still show the original page order as it was created, so in the terminal it will still show the original page 1, page 2 and page 3 order. 

Setup:
 - Foundry Version: V12 stable, build 330. 
 - Game System Version: Twodsix - Cepheus & Traveller v. 5.5.1.
 - Terminal Module Version: V. 2.6.5.
 - Browser & version Google chrome v. 127.0.6533.100

Active modules:
I have the following modules active:
![Capture1](https://github.com/user-attachments/assets/53e3b7ba-9559-47ea-a32d-e328d71e4cfb)
![Capture2](https://github.com/user-attachments/assets/75dee276-67b6-4e17-a673-3fd6b6aef934)

**Additional context**
I've noticed that i've been able to work around this bug by changing the page's position in the journal JSON file and then uploading the edited JSON file to replace the old journal. I had to move the page position in the JSON file, it wasn't enough to edit the "sort" string.

**Comment by Upgradecap** [comment]
Ah, ok! Thanks for the response, then i'll wait for the new update. Love your work!

**Comment by CodaBool** [comment]
just a quick update on this. I have a included this in the major update I'm going to release later this month.
It's working great. I mostly need to just test that things are stable before putting the update out.

It will only be for Foundry V12+ since I'm no longer supporting new features for V10-11 once this update comes out.

**Comment by CodaBool** [comment]
version 3 has been released.

> a reminder that this is V12+ only since I'm no longer supporting new features for V10-11 once this update comes out.

A detailed post about it is [here](https://codabool.itch.io/terminal/devlog/786464/terminal-v30)
