### ISSUE TITLE
[BUG] - Cannot Link Journal to Terminal Foundry V12

### ISSUE THREAD

**Issue by CalamitousGypsy** [CodaBool/terminal#17]
**Describe the bug**
Clicking the journal icon on the Terminal tab of a MATT tile minimizes the tile property window, prompts to click on a JOURNAL to connect the terminal; however, when I click on a journal on the sidebar it does not do anything except open the journal as a window.  Closing the MATT tile cancels the click listener.

 - Foundry Version: V12 Build 331
 - Game System Version: Savage Worlds Adventure Edition 4.1.1
 - Terminal Module Version: 3.1.2
 - Browser & version TheRipper93's Foundry VTT Desktop Client https://wiki.theripper93.com/free/vtt-desktop-client

**Active modules:**
![image](https://github.com/user-attachments/assets/8926ccb9-9215-4f3f-9f58-4be6904f26e5)
![image](https://github.com/user-attachmentsD/assets/f1dd3946-c9b4-4fbe-8313-7742b9bcffe7)
![image](https://github.com/user-attachments/assets/53f9f57c-5a8b-4832-8eca-4f71de650bdd)
![image](https://github.com/user-attachments/assets/862a9b8a-dd06-4462-b8f9-bfe3e20e1e5c)
![image](https://github.com/user-attachments/assets/4af8e879-7892-4eee-ac2e-f9807ce03d1c)
![image](https://github.com/user-attachments/assets/1196aad4-2ee6-4983-ad36-0ad5821b4b44)
![image](https://github.com/user-attachments/assets/9d0066a4-ba55-485c-bff8-84ebd59b0bb5)

**Additional context**

**Comment by CodaBool** [comment]
I'll do some testing but my gut feeling is a module conflict.

If you are willing there are two pieces of debugging that would really narrow this down:

1. [open your development console](https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).) and attempt it again. Post a screenshot if you seen any error messages in the console.

2. try is disabling all of the modules but Terminal and see if the issue still happens.

**Comment by CalamitousGypsy** [comment]
Absolutely, thank you so much for responding.

Unfortunately, nothing in the Dev console.  I'll attempt disabling and all and checking as well.

![image](https://github.com/user-attachments/assets/79a65375-b7e6-44b2-912f-d7ab7f390543)

**Comment by CalamitousGypsy** [comment]
I tried something crazy, not sure why it worked--I may have some setting enabled.  I tried ctrl click, shift click on journals in the sidebar but nothing worked.

However, alt + left click on the journal in the sidebar **did work.**  I was able to replicate this a few times, and able to activate the tile once enabled with a token standing on it!

I hope this helps.  If I can do anything else, let me know!

**Comment by CodaBool** [comment]
So, this is with Ripper's desktop app mode right? Does it behave the same with a regular browser?

**Comment by CalamitousGypsy** [comment]
It's a free desktop executable built with Chromium.  Unfortunately, I'm not super tech savvy, but it behaves seemingly identically to what I'd expect in a web browser but better performance (even down to F11 opening the dev tool).

**Comment by CodaBool** [comment]
Someone else has ran into this issue as well and provided some insight. @CalamitousGypsy Seems this is a conflict with the module "Monk's Enhanced Journal". I should be able to get started on a fix to publish later this week.

**Comment by CodaBool** [comment]
found the root cause, was able to fix this in 3.1.4

Thank you for the bug report :100:
