### ISSUE TITLE
apply marco switch sence after Terminal Invalid.

### ISSUE THREAD

**Issue by Rosataker** [CodaBool/terminal#2]
I found that Terminal can use marco, so I used it with scene switching, but when I switched scenes, the original function was disabled.

Please forgive me for using GOOGLE Translate.

![未命名](https://github.com/CodaBool/terminal/assets/26018418/929d91d9-afe9-4ea9-9b5f-1bf803bde184)
![未命名2](https://github.com/CodaBool/terminal/assets/26018418/91ba3257-1e8a-471d-b35f-37ca590e64d3)
![未命名3](https://github.com/CodaBool/terminal/assets/26018418/64e04905-5bf8-434b-9888-49ed678a1f3c)
![未命名4](https://github.com/CodaBool/terminal/assets/26018418/1e6a4ea0-10f1-47f1-94d0-61edc31208bb)

**Comment by CodaBool** [comment]
Thanks for the info 🌞

I'll try to reproduce this this weekend. And get a fix out.

Do you think you could give numbered steps for how to reproduce this?

For example:

1. I do this first
2. I do this next
3. etc...

**Comment by CodaBool** [comment]
To clarify, you are using the macro to switch scenes?

If that's the case I don't know if I will be supporting something like that. It's not the main purpose of the module. A better fit would be using the module [monks-active-tile](https://github.com/ironmonk88/monks-active-tiles/). 

I attached a video on how you could do that. Best of luck 🐱

https://github.com/CodaBool/terminal/assets/61724833/eb52db91-4a67-4216-9dd5-f92e92104495

**Comment by Rosataker** [comment]
Ok, thanks for your help, I think I can use other methods to achieve the effect I'm hoping for!
