### ISSUE TITLE
Skill check doesn*t work within the Alien System

### ISSUE THREAD

**Issue by Zettgeschehen** [CodaBool/terminal#4]
Hello, I have tried to activate the CHeck skill for the Alien system. When activating (e.g. before login) nothing happens, when deactivating a slider appears for a millisecond and then disappears again. If I leave the skill check activated (before login) nothing happens. Is it because I am logged in as a GM (I have a token on the scene to try it out) or is there possibly a conflict with another module? Or could it be a translation problem? I use  german as default language, so all attributes in the character sheet are not written in english.

Setup:
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Spielsystem: alienrpg, 3.1.7

**Comment by CodaBool** [comment]
Yeah. I'm away at the moment but give it a try as a non-GM player. 

Nearly all "checks" get skipped when playing as GM. I'm guessing that's what's going on there
