### ISSUE TITLE
Foundry freeze when I'm trying to use terminal with monk active trigger

### ISSUE THREAD

**Issue by Zhikann** [CodaBool/terminal#6]
Foundry freeze when im trying to use the module with monk active trigger.
I just want to trigger the module on click (see screenshot).

**To Reproduce**
1. Right click on a tile
2. On the terminal tab, Untick enabled
3. On the trigger tab setup -> enable ->  click on the triggers tab -> Trigger tile -> current tile
4. No logs error just freezing (need to restart foundry) 

**Expected behavior**
Trigger terminal with left click

**Screenshots**
![image](https://github.com/CodaBool/terminal/assets/98021260/8d3ec5e7-d9c4-49e1-ab3a-8d2f55d720a5)
![image](https://github.com/CodaBool/terminal/assets/98021260/a8d0ee56-a27f-4fc0-a870-a6b2a5bf3ed1)
![image](https://github.com/CodaBool/terminal/assets/98021260/5f22b0c3-45af-43a3-87f2-5374ed41242d)

**Setup:**
 - Foundry Version: 11.315
 - Game System Version: Trying in 2 game system ( Cyberpunk red and Genesys)
 - Terminal Module Version: [2.0.0 & 2.0.1]
 - Browser & version [Foundry VTT]

**Active modules:**
 - Dice So Nice!
 - Terminal 
 - Monk active trigger

**Comment by CodaBool** [comment]
I've gone through the steps you outlined. When you say freeze, do you mean that nothing happens or you have to reload the page and its unresponsive?

I have an alternative approach that you could take (using the Terminal compendium macro) but want to make sure I'm not crashing anyone's browser with my code first.

Also does this "Trigger Action" section below match yours? That's one configuration that I'm not sure if I reproduced correctly

![image](https://github.com/CodaBool/terminal/assets/61724833/65a02689-ca65-4906-b18e-9e69b621408c)

**Comment by Zhikann** [comment]
Hello, 

Yes I have the same trigger action.

When I mean a freeze, the FoundryVTT.exe did not respond, I have to restart the software.

**Comment by CodaBool** [comment]
Ok, I haven't been able to reproduce that then. 

I'm going to be away from my desk for a bit but I put out a new version, 2.0.2, which should fit your usage.

The essential part is to use the macro from the compendium called "Open Terminal for specific user".

![image](https://github.com/CodaBool/terminal/assets/61724833/61561584-c9e0-4440-98a8-bf83fcb9d085)


And supply the tile ID as the argument and set it to triggering player

![image](https://github.com/CodaBool/terminal/assets/61724833/8ea5c9e3-8159-4986-a878-49c987aa9cfc)


Let me know how that works for you.

I'll see if I can figure out why that's crashing on you though later today
