### ISSUE TITLE
[REQUEST] - SHORT DESCRIPTION HERE

### ISSUE THREAD

**Issue by franckflo** [CodaBool/terminal#8]
Hi, I'm planning an Alien game and am on the fence about buying this module to supplement my campaign. There are a couple features I'd love to see added to improve player experience:

-  A "text scrolling" feature that would emulate the way terminals display text in the Alien movies, letter by letter. It would be even better if there was an optional sound effect (keyboard keystroke, typewriter sound, etc). Imagine the immersion :).

- The same tool, but in realtime chat or terminal window, to emulate the chat between Neo and Trinity for example

- Have an interface for the GM to reveal part of the journal entry to the players in real time.

Do you think these features could be added?

**Comment by CodaBool** [comment]
I've been meaning to look into text animations. That is definitely something I will try to implement in the next few months. 

You're the second person to request a way to chat. For now I'd recommend this new module that popped up a few months ago called Console. It's free and allows you to chat in a stylized window. 

If I implemented a chat feature it'd be a lot more code. So, I'm going to tackle some easier things I've had on my list for a while now. 

Can you expand on the revealing text idea. When would you do that / what is this simulating? How would the GM reveal it? 

There is currently support to have a whole page "encrypted" where the player needs to perform a skill check to reveal a page. Would this work for your purposes?

**Comment by franckflo** [comment]
Neato, I think the text animation with SFX would improve immersion  a lot. It's such a cool part of this type of scifi movies.

Yep, I understand the chat feature is a bit outside of this module's purview: Thanks for the advice about Console, I'll look into it :)

The reveal feature: The way I imagine it, the GM side of the journal would have some kind of button that would allow them to reveal the content of the journal per segment. Maybe the segment could be designated ahead of time with some kind of HTML marker; a beacon of sorts.  Yep, the encrypted tool is pretty neat :).

All right, I'm sold: I'm going to purchase your module to thank you for your hard work and encourage further developpement. Keep up the good work !

**Comment by CodaBool** [comment]
Latest update 2.6.0 adds a few new style settings. One of which is a text animation. 

Enjoy

**Comment by franckflo** [comment]
Wonderful. Thanks ! Were you able to add some sound to the animation ?
