### ISSUE TITLE
[REQUEST] - Features

### ISSUE THREAD

**Issue by gudnyt** [CodaBool/terminal#9]
A few features i'd like to see implemented:

1) Removal of token dependency- Can we add the ability to trigger on mouse click? Maybe create a call so monks active tiles can trigger it.
2) Add ability to load a scene or trigger a tile- You can expand the usage of this mod to allow the terminal to be able to change scenes or active tiles

**Comment by CodaBool** [comment]
This should be doable with the included macros.

Check your compendium tab and pick which effect you want

- open for one user
- open for all connected users

You'll probably want the one user effect. All that is needed as an argument for this macro is the tile id that has the associated Terminal.

That should work for you.


## extra stuff
An important thing to note is that most features of Terminal expect you to be on the same scene as Terminal.

Meaning if you try to open a Terminal in a different scene or have the Terminal open while switching scenes. Most features will break. 

There is some validation to let you know early but I have not covered all possibilities. Especially with macros, they kind of expect you know what you're doing at the moment.
